# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1ba0e069721f93052cfa0eb3b26fc38"
application_url = "https://tender-answers-canyon-cap.trycloudflare.com"
embedded = true
name = "budnles-upd"
handle = "budnles-upd"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://tender-answers-canyon-cap.trycloudflare.com/auth/callback",
  "https://tender-answers-canyon-cap.trycloudflare.com/auth/shopify/callback",
  "https://tender-answers-canyon-cap.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
